- Gemfile
- Gemfile.lock
- lib/g10_certification_test_kit.rb
- lib/g10_certification_test_kit/patient_context_test.rb
- lib/g10_certification_test_kit/restricted_resource_type_access_group.rb
- lib/g10_certification_test_kit/smart_ehr_practitioner_app_group.rb
- lib/g10_certification_test_kit/smart_limited_app_group.rb
- lib/g10_certification_test_kit/smart_public_standalone_launch_group.rb
- lib/g10_certification_test_kit/smart_standalone_patient_app_group.rb
- lib/g10_certification_test_kit/unrestricted_resource_type_access_group.rb
- spec/g10_certification_test_kit/patient_context_test_spec.rb
- spec/g10_certification_test_kit/resource_access_test_spec.rb
This branch updates the tests to use `oauth_credentials` so that they can automatically refresh access tokens.
> FI-1407: Refresh tokens

- lib/onc_certification_g10_test_kit.rb
Remove required searches from delayed resources ('Encounter', 'Location', 'Organization', 'Practitioner', 'PractitionerRole', 'Provenance') for g10-certification-test-kit
> FI-1640 Remove searches from delayed resources

- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- lib/onc_certification_g10_test_kit/profile_guesser.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
Allow Medication and Location tests in Bulk Data Export Validation to omit instead of skip if the respective resources are not returned.
> Omit location medication

- Gemfile.lock
- Rakefile
- config/presets/inferno_reference_server_preset.json
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- onc_certification_g10_test_kit.gemspec
- spec/onc_certification_g10_test_kit/bulk_data_authorization_spec.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_spec.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
This branch adds an `additional_patient_ids` input. The standalone and ehr launches set `patient_id`. The user can input `additional_patient_ids`. `patient_id` and `additional_patient_ids` are combined into a single input `patient_ids` which is passed along to the single patient api tests.
> FI-1478: Fix patient id inputs

- lib/onc_certification_g10_test_kit/bulk_data_authorization.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
In the current state, some ugly '\n' get shown in JSON/YAML representation. This fixes that.
> Reformat line breaks in input description

- lib/onc_certification_g10_test_kit/bulk_data_group_export.rb
- spec/fixtures/CapabilityStatement.json
- spec/onc_certification_g10_test_kit/bulk_data_group_export_spec.rb
Reported issue about having a server on a url that does not match our reference server and hardcoded fixtures.  I'm not sure how much of this URL is the _"base"_.
This is the regex: `%r{^http(s)?://.*/OperationDefinition/group-export(\|\S+)?$}`
Added a test, watched it pass/flip both ways on http|https, version number at the end, before this PR, the whole red/green loop.  So I'm confident in this fix but not on what we want to consider the base url.
Related: #51
> Relax regex on bulk data server group export url

- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
This PR fixes GitHub Issue #60 
The changes allows Bulk Data File download testing accept HTTP Redirect status 301/302/303/307
When requesting redirect endpoint, Bulk Data client does NOT send authorization header.
> FI-1522 Accept Redirect 301/302/303/307 for Bulk Data file download

- .gitignore
Make sure `tmp` folder exists to avoid terminology build error (#68).
> FI-1519: Add tmp folder

- lib/onc_certification_g10_test_kit/visual_inspection_and_attestations_group.rb
This PR updates title and description of Visual Inspection and Attestation test 6.6.05/ATT-05 
from:
Health IT Module attested that refresh tokens are valid for a period of no shorter than three months.
to:
Health IT Module attested that it is capable of issuing refresh tokens  that are valid for a period of no shorter than three months.
This  PR fixes Github Issue #45
> Update title and description for one visaul inspection test

- lib/onc_certification_g10_test_kit/bulk_data_group_export.rb
- spec/fixtures/CapabilityStatement.json
- spec/onc_certification_g10_test_kit/bulk_data_group_export_spec.rb
See the test description in the PR for an explanation of how this works.  I do not think that we should allow ( 'export' or 'group-export' ) as the name, because 'group-export' does not make sense.  We could just enforce 'export', but it seems like there isn't complete consensus here, particularly since our reference server does not send back 'export' here.  I think the safe thing to do is to just downgrade the name check to a warning (which we avoid in general, but I still am pretty sure that 'export' as the name is the only right thing to do given we are requiring it be mounted there in later tests).
However, we can safely require that some operation is defined on the Group resource, which allows us to still have a failing condition on this test so we don't have to remove it altogether. …
> Reduce operation.name != export to warning on Group operation.

- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- spec/onc_certification_g10_test_kit/single_patient_api_group_spec.rb
#93 describes a nil-safety issue with the `additional_patient_ids` input. This branch makes it nil safe.
> FI-1533: Fix nil safety in additional_patient_ids

- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
This PR changes Bulk Data export validation so that
* it validates all lines/resources
* it saves validation errors and warnings from the first failed line/resource
* it returns result message with the count of failed lines/resources
This PR fix Github Issue #104
> FI-1524 bulk validation

- Gemfile.lock
- README.md
- lib/onc_certification_g10_test_kit/configuration_checker.rb
- lib/onc_certification_g10_test_kit/version.rb
This branch adds a configuration error message when using a development version. When not using an official release, the version will end in `.dev`.
> FI-1546: Dev versioning

- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
Updates the omit message when no Medication/Location resources are provided in bulk data to explicitely state that they are not required, so user knows that this is not an error (if they do not know what 'omit' means).  This language is used in v1.9 and it makes sense to carry it forward here.
See #111 for screenshots.  This adds '<resourcetype> resources are optional.' to the omit message.
> FI-1553 Update bulk data omit message to be consistent with v1.9

- README.md
- lib/onc_certification_g10_test_kit/bulk_data_authorization.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/multi_patient_api.rb
The regulation is technically to v1.0.1 of Bulk Data, which has slightly different links than v1.0.0.  This was raised to ONC via their comment portal.  Technically the changes are very small and do not affect the parts that we linked to generally, but we need to be very precise.
I also found a link to build.fhir.org separately which is incorrect.
> FI-1556 Updates links in descriptions to correct version of Bulk IG per regs.

- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
We do this after every release to ensure that nobody is running an upgraded version from `main` that is functionally different than the version number indicates (unless they want to -- they can ignore the error).
> Update version to .dev

- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
This branch improves the g10 suite's wait messages. WIP because this branch will require:
* a new core release which includes https://github.com/inferno-framework/inferno-core/pull/211
* a new SMART test kit release which includes https://github.com/inferno-framework/smart-app-launch-test-kit/pull/25
Screenshots of the updated wait messages:
> FI-1474: Improve wait messages

- lib/onc_certification_g10_test_kit/resource_access_test.rb
Resource type was incorrectly hard coded for searches requiring status.
> Fix hard coded resource type in resource access test

- README.md
While we document how to run Inferno in a multi-user environment via the Inferno Framework documentation, this is pretty hidden for the average 'test kit' user, but is important for those running this on a shared server.  I've added a section on this in the README to provide more visibility to this option in the (g)(10) test kit.
An example where this visibiilty would have helped:
https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Inferno.20Local.20Install.20.2E.2E.2E.20issues.20in.20tests.20completing.3F
> Add README reference to PostgreSQL installation for multi-user installs.

- config/presets/inferno_reference_server_preset.json
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
**Note for release notes: this removes an input so presets should be updated.  A non-fatal warning will be issued in the console otherwise.**
This updates the input to the Limited App Launch test to use the same inputs as in the Standalone App Launch test because the purpose of the test to ensure that the user has control over which scopes are granted, and that an app doesn't have to request different scopes (which the user likely will not have control over).  This makes this test consistent with the behavior in <v1.9, as it was inadvertently changed.
To test, verify that the limited launch still works properly, and that whatever scopes and pkce-related fields that are used in the Standalone App Launch test are persisted in this input.  Also, the pkce-related fields will now be locked. …
> FI-1639 Update limited app launch to have launch use same inputs as in Standalone App Launch test

- lib/onc_certification_g10_test_kit/multi_patient_api_stu1.rb
- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
For this release, I think it is better to not have the standards version numbers in the test titles.  Part of the issue is that while convenient for us to verify that the right code is being loaded, it isn't quite 100% accurate because many of our tests actually cut across multiple standards.  Also, for this release, since most users won't use the SVAP versions of standards (requires downloading and changing feature flags), displaying version numbers is premature.
This update just changes tests 4 and 5 to not state (US Core v3.1.1 and STU1), and fixes a small typo in another test description.
> Remove standards version from test titles and fix typo.

- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu1.rb
I do not want to change test names until the next release -- this was one that was missed:
```
5.2 Group Compartment Export Tests STU1
```
> Remove STU1 label from Group Export test for now.

- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
This ensures there is a warning indicating that the copy they are running is not a stable release for certification.
> Update to .dev verison.

- lib/inferno/terminology/expected_manifest.yml
- lib/inferno/terminology/fhir_package_manager.rb
- lib/inferno/terminology/loader.rb
- lib/inferno/terminology/tasks/create_value_set_validators.rb
- lib/inferno/terminology/tasks/download_fhir_terminology.rb
- lib/inferno/terminology/value_set.rb
- resources/value_sets.yml
This branch updates the terminology build to include US Core 4.0.0 terminology. The main changes involve adding US Core 4 and VSAC (since it's used by US Core 4) to the list of FHIR packages which will be downloaded, and adding some special handling to avoid processing every VS in VSAC.
> FI-1649: Update terminology build for US Core 4

- lib/onc_certification_g10_test_kit/visual_inspection_and_attestations_group.rb
Attestations for `Patient.name.suffix` and `Patient.period` are only needed when using US Core 3 because the requirements are included in the profiles for US Core 4 & 5 and tested automatically.
> FI-1678: Disable obsolete attestations

- lib/onc_certification_g10_test_kit/limited_scope_grant_test.rb
- lib/onc_certification_g10_test_kit/restricted_resource_type_access_group.rb
- lib/onc_certification_g10_test_kit/unrestricted_resource_type_access_group.rb
This branch adds resource access tests for `ServiceRequest` when using US Core 5. US Core 5 also adds profiles for `QuestionnaireResponse` and `RelatedPerson`, but `QuestionnaireResponse` support is optional, and the only required search for `RelatedPerson` is by `id`, which we won't know immediately after a launch.
> FI-1676: Update resource access tests for US Core 5

- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- lib/onc_certification_g10_test_kit/profile_selector.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
Adds additional resource for us_core_5:
* ServiceRequest
Adds additional optional resource types for us_core_5 (omits if none provided):
* RelatedPerson
* PractitionerRole
* QuestionairreResponse
Updates logic for Condition and Observation for choosing relevant profiles.  For Observation relating to SDOH, it only validates against the SDOH profile and not the parent 'survey' profile.
Updated all descriptions as well.
I didn't add self-tests.  I wasn't sure how to handle this with Features and options.  Maybe this is something we can circle back on next month?
To test, update .env to have:
```
US_CORE_4_ENABLED=true
```
And take a look at the US Core 5 vs. US Core 4/3 tests when enabled.
> FI-1673 Initial pass at bulk data us core 5 validation.

- lib/onc_certification_g10_test_kit/limited_scope_grant_test.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group_stu2.rb
- lib/onc_certification_g10_test_kit/smart_scopes_test.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- lib/onc_certification_g10_test_kit/unrestricted_resource_type_access_group.rb
This branch adds support for SMART v2 scopes. When using SMART v2, v2 scopes are required for for the Standalone, Limited, and EHR launches.
> FI-1689: SMART v2 scopes

- lib/onc_certification_g10_test_kit/encounter_context_test.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/well_known_capabilities_test.rb
Encounter is in USCDI v2, so the Encounter context should be tested when using US Core 5. If you run the EHR launch with US Core 5, you should see the encounter test.
> FI-1658: Add encounter context test to EHR launch group

- lib/onc_certification_g10_test_kit.rb
- spec/onc_certification_g10_test_kit/resource_validation_spec.rb
Add filter for validator's invalid coding error message.
How to test:
Run latest (g)(10) test suite.
Patient validation test shall pass
> Add filters for invalid Coding error

- lib/onc_certification_g10_test_kit/well_known_capabilities_test.rb
- spec/onc_certification_g10_test_kit/smart_well_known_capabilities_test_spec.rb
This branch address the issue in #254 which is caused by the test config being modified in a persistent manner.
If you check out the first commit in this branch, there will be a failing unit test.
> FI-1707: Fix context-ehr-encounter requirement

- lib/onc_certification_g10_test_kit/profile_selector.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
This branch prevents Head Circumference (not percentile Head Circumference) resources in the bulk data tests from being validated when US Core 3 is being used (reported in #238).
> FI-1702: Fix head circumference bulk data profile

- README.md
This branch updates the terminology build instructions so that following them always results in running the current build. By following the previous instructions, it was possible to use an old image resulting in an invalid build (see #243).
> Clarify terminology instructions

- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu1.rb
- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- lib/onc_certification_g10_test_kit/resource_access_test.rb
Check that json is valid to prevent purple json parsing errors (#275).
> FI-1730: Check that json is valid before parsing

- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- lib/onc_certification_g10_test_kit/g10_options.rb
- lib/onc_certification_g10_test_kit/limited_scope_grant_test.rb
- lib/onc_certification_g10_test_kit/profile_selector.rb
- lib/onc_certification_g10_test_kit/restricted_resource_type_access_group.rb
- lib/onc_certification_g10_test_kit/smart_app_launch_invalid_aud_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
- lib/onc_certification_g10_test_kit/smart_scopes_test.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- lib/onc_certification_g10_test_kit/unrestricted_resource_type_access_group.rb
- lib/onc_certification_g10_test_kit/visual_inspection_and_attestations_group.rb
- lib/onc_certification_g10_test_kit/well_known_capabilities_test.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
- spec/onc_certification_g10_test_kit/smart_well_known_capabilities_test_spec.rb
This branch adds a module to handle various suite options in g10 and reduce the duplication of magic strings throughout the codebase. Waiting on #272 to be approved before updating profile selector.
> FI-1724: Encapsulate suite options

- lib/onc_certification_g10_test_kit/configuration_checker.rb
If you look at the g10 config info messages on inferno-dev, you should see this, which means this works:
> Fix CodeSystem metadata path

- lib/onc_certification_g10_test_kit.rb
This fixes terminology validation.
If you run the tests against inferno-dev, you should see three terminology errors in the patient tests that you don't see on `main` (see #320).
> FI-1780: Fix terminology checking

- lib/onc_certification_g10_test_kit/profile_selector.rb
Clinical test observations in US Core 5 were not being correctly identified in the bulk data tests due to an incorrect system url (see #327).
> FI-1781: Fix clinical test observations in bulk data

- lib/onc_certification_g10_test_kit/patient_scope_test.rb
- lib/onc_certification_g10_test_kit/short_id_map.yml
- lib/onc_certification_g10_test_kit/smart_ehr_patient_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_patient_launch_group_stu2.rb
- spec/onc_certification_g10_test_kit/smart_ehr_patient_launch_group_spec.rb
- spec/onc_certification_g10_test_kit/smart_ehr_patient_launch_group_stu2_spec.rb
This branch adds tests to verify that patient-level scopes are received during the EHR Launch with Patient Scopes (see #330).
> FI-1779: Verify EHR patient launch scopes

- Gemfile.lock
- lib/onc_certification_g10_test_kit/terminology_binding_validator.rb
- lib/onc_certification_g10_test_kit/version.rb
`Condition/260` on  inferno-dev has been updated to include the US Core 5 categories. The `Condition Problems and Health Concerns` tests will fail against inferno-dev on `main`, but should pass on this branch (see #340).
> FI-1789: Add special case for us core 5 Condition.category terminology

- Dockerfile.terminology
- Rakefile
This branch updates the terminology build process to be compatible with Ruby 3 (see #342).
> FI-1791: Fix terminology build for Ruby 3

- lib/onc_certification_g10_test_kit/terminology_binding_validator.rb
- spec/onc_certification_g10_test_kit/terminology_binding_validator_spec.rb
This is part of fix for GitHub Issue https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/361.
This PR relates to US Core Test Kit PR: https://github.com/inferno-framework/us-core-test-kit/pull/94
This PR changes:
* Replace the validate logic for us-core-5-condition with a more general logic for any binding in a mandatory slice with `required` binding strength
* Add unit test
Testing:
Verify all unit tests pass
> FI-1792 Terminology Validator handles binding with required binding slice

- lib/inferno/terminology/terminology_validation.rb
Fix a bug prevented mime-types with charsets from failing terminology validation when they don't have a system (see #369).
> FI-1826: Handle validation of mime-type codes without a system

- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- lib/onc_certification_g10_test_kit/profile_selector.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
This branch updates the profile selector used by bulk data to allow resources to match with multiple profiles (see #380). If you run the bulk data tests on `main` using US Core 5, the Observation test will fail because not all MS fields are found because most of the resources that could match one profile have instead been matched with another. The Observation bulk data tests should pass on this branch.
> FI-1834: Allow multiple bulk profiles

- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
This branch fixes the patient id list input for bulk data so that it is now optional as stated in its description.
> FI-1670: Make patient id list optional for bulk data tests

- lib/onc_certification_g10_test_kit/onc_program_procedure.yml
- lib/onc_certification_g10_test_kit/short_id_map.yml
- lib/onc_certification_g10_test_kit/visual_inspection_and_attestations_group.rb
Adds attestation regarding extending the life of refresh tokens. I based the language of the attestation from the test procedure, and provide more details in the 'About' section.
Language from the test procedure:
> AUT-PAT-22: The health IT developer demonstrates the ability of the Health IT Module to issue a refresh token valid for a new period of no shorter than three months without requiring re-authentication and re-authorization when a valid refresh token is supplied by the application according to the implementation specification adopted in § 170.215(a)(3).
I felt like it would be useful to mention that this is different than the refresh token duration attestation in the  'about' section, as I figured that would be a common question.  That one is:
> 9.10.05 Health IT Module attested …
> fi-1748 Adds attestation to ensure that systems are capable of extending authorized access of refresh tokens (Minor-version change)

- lib/onc_certification_g10_test_kit/patient_scope_test.rb
- lib/onc_certification_g10_test_kit/smart_ehr_patient_launch_group.rb
Some links in the EHR Launch with Patient Scopes Group went to the incorrect IG version (see #389).
> FI-1869: Fix smart IG links in EHR launch with patient scopes

- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu1.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu2.rb
- lib/onc_certification_g10_test_kit/onc_program_procedure.yml
- lib/onc_certification_g10_test_kit/short_id_map.yml
- spec/onc_certification_g10_test_kit/bulk_data_group_export_stu2_spec.rb
Bulk data v2 requires specific behavior for status requests for cancelled bulk exports (see #385).
> FI-1765: Check status of cancelled bulk export (Minor Version Change)

- Gemfile.lock
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_scopes_test.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- spec/onc_certification_g10_test_kit/smart_scopes_test_spec.rb
This branch updates the scope validation test to also validate that patient/user-level scopes are received rather than only validating that those scopes are requested (see #333).
> FI-1868: Validate granted scope types

- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_4_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_5_api_group.rb
Just updates language in 4.1, 5.1, 6.1 which now shouldn't have the 'Patient + 1' requirement.
> FI-1902: Update CapabilityStatement language to be USCDI-specific

- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu1.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_stu1_spec.rb
This PR fixes GitHub Issue #420 
What changed:
Update Bulk Data export timeout skip message to include: time used, next poll time, timeout setting.
> FI-1959 Update Bulk time out skip message

- config/presets/inferno_reference_server_preset.json
- lib/onc_certification_g10_test_kit.rb
This branch updates the g10 suite to use a different validator based on the US Core version.
You can test this by adding `puts us_core_version_requirement` inside the `perform_additional_validation` block. Then run some tests which perform validation, and you'll see output like `{:us_core_version=>"us_core_5"}` depending on which version you selected.
> FI-1946: Add version-specific validators

- lib/onc_certification_g10_test_kit/smart_scopes_test.rb
- spec/onc_certification_g10_test_kit/smart_scopes_test_spec.rb
This branch fixes a bug which cause a failed assertion to state that a requested scope was invalid when it's actually a received scope which is invalid.
> FI-1982: Fix bad scope message

- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/smart_invalid_pkce_group.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group_stu2.rb
JIRA Ticket: https://oncprojectracking.healthit.gov/support/browse/FI-2011
To Test:
- Review the [Walkthrough](https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki/Walkthrough#inferno-g10-standardized-api-test-kit-walkthrough) to check that the changes stated in the ticket are accurately reflected.
- On the (g)(10) test kit option page, check that the last sentence of the text on the left says "click 'Start Testing' to begin testing"
- In Additional Tests, the long name of "SMART Public Client Launch" should now be "SMART Public Client Standalone Launch with OpenID Connect"
- For the "User Action Required" modal that pops up during the "Limited Access App" tests, the modal should now display with extra spacing like the image below, to improve readability.
**Question**: Do …
> Minor Visual Fixes

- README.md
The approved standards list in the README looked a bit off to me; it looks like I didn't properly translate bullets properly into markdown.  Figured I'd fix it real quick while looking at it (doesn't seem worth a matching Jira ticket here)
> Fix formatting of approved standards in README.

- lib/onc_certification_g10_test_kit/configuration_checker.rb
In anticipation of the validator `/version` endpoint returning a JSON (see https://github.com/inferno-framework/fhir-validator-wrapper/pull/62 ), this PR updates the logic for checking the validator version.
Because previously the version check was just a basic string comparison, using JSON introduces some new ways it could fail: the JSON might not parse, or it might not contain the right key, etc. This set of changes is intended to be simple and minimal but not break if anything goes wrong. 
**Testing Guidance**:
Make sure an "old" instance of the validator that returns a string version doesn't crash. Make sure when using a validator returning JSON that this compares the version number against the value of the `inferno-framework/fhir-validator-wrapper` key as expected.
> FI-1223: Support the validator /version returning a JSON

- docker-compose.background.yml
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/configuration_checker.rb
The validator wrapper is being upgraded to use the most recent version of the HL7 validator (6.0.21 as of now, see https://github.com/inferno-framework/fhir-validator-wrapper/pull/61), and that version of the validator produces some slightly different output compared to the version we previously used (5.6.93):
1. Code displays that do not match the official display are now errors by default. This can be changed to match the old behavior with the environment variable "DISPLAY_ISSUES_ARE_WARNINGS" set to true. 
2. There's now an error message received when testing US Core 3.1.1 related to a constraint that cannot be met due to a bad profile, see message below. This was seen previously with slightly different text ( https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Pulse.20Oximetry.20 …
> FI-1995: Changes for HL7 validator v6.0.21

- docker-compose.background.yml
- lib/onc_certification_g10_test_kit/configuration_checker.rb
Bumps the Validator dependency to release v2.3.1. 
2.3.1 sorts the IGs it loads to ensure a consistent order, and ensures the `/version` endpoint is always accessible, so no changes to the interfaces and no other changes are required here.
> Bump Validator dependency to v2.3.1

- config/presets/g10_reference_server_preset.json
It doesn't make sense for the preset within the g10 test kit to point at the same host as Inferno. It should just point to our deployed reference server.
> FI-2372: Fix preset

- lib/onc_certification_g10_test_kit/short_id_map.yml
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
The Encounter context test was missed when adding tests for US Core 6. This branch adds it for SMART 1 & 2.
> FI-2406: Add Encounter context for US Core 6

- docker-compose.background.yml
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/configuration_checker.rb
Bump the validator to release 2.3.2 and update the message filters to handle new error messages. Note there are 2 new messages, one a slight variation of an existing message ("_ is not in the value set" vs "_ was not found in the value set") and one brand new "A definition for CodeSystem '.*' could not be found, so the code cannot be validated". 
I extracted the message regexes into a list only because the new message text is long and this felt cleaner than a multi-line regex
> FI-2423: Bump validator dependency to v2.3.2

- config/presets/g10_reference_server_preset.json
- lib/onc_certification_g10_test_kit/token_revocation_group.rb
ONC has updated their requirement for token revocation to be clear that they must be complete within one hour of the patient request.  See [rule](https://www.federalregister.gov/d/2023-28857/p-3013).  This goes into effect March 11.
**NOTE: this changes the name of a test. I do not believe this has any significant downstream effects (e.g. breaking the test mapping across versions, for example).  But if it does let me know.**
> FI-2564 Update attestation for token revocation to include time limit.

- README.md
- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/onc_program_procedure.yml
This PR fixes JIRA FI-2645 by removing US Core 5.0.1 from descirptions from 
* READ.me
* Bulk Data validation test 
* Test Procedure mapping
> FI-2645 Remove US Core 5.0.1 from descriptions

- docker-compose.background.yml
- lib/onc_certification_g10_test_kit/configuration_checker.rb
Just bumps the validator version to the latest, 1.0.52: https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/releases
The validator image is available on Docker Hub https://hub.docker.com/repository/docker/infernocommunity/inferno-resource-validator/general
Impacts:
- There should be no new validator errors compared to the previous version, for US Core 3, 4, or 6. 
- There should be better logging in the validator logs.
> FI-2667: Bump validator version to 1.0.52

- lib/onc_certification_g10_test_kit.rb
Quick fix for the tx.fhir.org validation errors that we have seen slip through, as in #523 and #524. Now any message containing `[Error from tx.fhir.org/r4:` will be ignored.
Testing this is tricky since this error is flaky. I used https://mockoon.com/ to create a mock service that always returned a bad error, with the attached response. [validate.txt](https://github.com/user-attachments/files/16086942/validate.txt)  I got this response from validator.fhir.org using a DocumentReference with a bad mime type "junk/pdf". Note I replaced the sessionID field at the bottom with a mockoon template helper so the sessionID isn't consistent (the validator session startup job broke when every instance got back the same session ID)
> Add error filter for tx validator errors

- lib/onc_certification_g10_test_kit/patient_context_test.rb
The patient context test is run in the context of original access token exchanges, as well as token refreshes, but its title did not accurately describe its behavior when used in the context of a token refresh (see #522).
This branch updates the title and description to something which should be accurate in both circumstances.
> FI-2838: Update patient context title and description

- lib/onc_certification_g10_test_kit/onc_program_procedure.yml
- lib/onc_certification_g10_test_kit/tasks/generate_matrix.rb
This branch updates the matrix generation to handle tests at different levels of nesting.
If you run `bundle exec rake g10_test_kit:generate_matrix` and examine the newly generated matrix, you should see:
- On the "Matrix" sheet, `9.14` should be identified as satisfying `AUT-PAT-28`.
- On the "Inferno Tests" sheet, all of the tests under `9.14` should appear.
This branch is on top of #537 because that PR contains the deeply nested tests which this change supports.
> FI-2981: Update matrix generation for deeply nested tests

- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/multi_patient_api_stu1.rb
- lib/onc_certification_g10_test_kit/multi_patient_api_stu2.rb
- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_4_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_6_api_group.rb
- lib/onc_certification_g10_test_kit/smart_app_launch_invalid_aud_group.rb
- lib/onc_certification_g10_test_kit/smart_asymmetric_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_patient_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_patient_launch_group_stu2.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_fine_grained_scopes_group.rb
- lib/onc_certification_g10_test_kit/smart_granular_scope_selection_group.rb
- lib/onc_certification_g10_test_kit/smart_invalid_pkce_group.rb
- lib/onc_certification_g10_test_kit/smart_invalid_token_group.rb
- lib/onc_certification_g10_test_kit/smart_invalid_token_group_stu2.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group_stu2.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- lib/onc_certification_g10_test_kit/smart_v1_scopes_group.rb
- lib/onc_certification_g10_test_kit/token_introspection_group.rb
- lib/onc_certification_g10_test_kit/token_revocation_group.rb
A pass at refining all test descriptions.  Besides updating the new tests, I attempted to clean up existing test descriptions to make them more consistent as well.  For example, being consistent about use of headers in descriptions.
I stuck to the high-level descriptions.  I did not dive into the second, third and fourth level descriptions here, as I don't think those are nearly as important.
> FI-2950: Improve test description

- lib/onc_certification_g10_test_kit/base_token_refresh_stu2_group.rb
See #548 for details of this issue.
To see the resolution, run group `9.12` with US Core 6 and SMART v2. [On prod](https://inferno.healthit.gov/suites/g10_certification/lwSEPAVZtns#g10_certification-Group06-g10_asymmetric_launch), the token refresh request in test `9.12.3.03` does not contain a `client_assertion`, so it is not using asymmetric auth. On this branch, that request will include a `client_assertion`, indicating that it is using asymmetric auth.
> FI-3038: Use token refresh stu2 test for token refresh with scopes in asymmetric launch group

- lib/onc_certification_g10_test_kit/smart_granular_scope_selection_test.rb
- spec/onc_certification_g10_test_kit/smart_granular_scope_selection_test_spec.rb
The Granular Scopes 9.15.2.09 failure indicates the absence of a prerequisite needed to verify the behavior, so it should be a skip rather than a failure. This PR changes this Granular Scopes test so that the test skips rather than fails if granular scope is requested.
> FI-3027: Granular Scopes Test Failure to Skip

- lib/onc_certification_g10_test_kit/smart_granular_scope_selection_group.rb
To pass the SMART Granular Scope Selection group, it is necessary not to grant all requested scopes, but the test titled: 'Token exchange response body contains required information encoded in JSON' was warning users that not all requested scopes were granted. 
This PR updates the SMART Granular Scope Selection group so that it adds the `ignore_missing_scopes_check` option to the imported `smart_standalone_launch_stu2` test group so that the warning is not displayed.
Run the SMART Granular Scope Selection group, and ensure that not granting all the requested scopes no longer adds a warning to the test titled: 'Token exchange response body contains required information encoded in JSON'.
> FI-3026: Fix Granular Scopes Group Token Exchange Requested Scopes Warning

- lib/onc_certification_g10_test_kit/g10_options.rb
- lib/onc_certification_g10_test_kit/profile_selector.rb
This ticket fixed FI-3391 Reference Bulk Data server should return valid SmokingStatus Observation resource with valueQuantity
* Update logic in profile_selector to handle additional US Core Smoking codes specified in US Core 7
Start (g)(10) test kit with US Core v7 and Bulk Data v2
Run Test Group 8 Multi-Patient API STU2
All tests shall pass
> FI-3391 Fix Could not find Observation.value[x]:valueQuantity in Bulk Data Testing

- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/multi_patient_api_stu1.rb
- lib/onc_certification_g10_test_kit/multi_patient_api_stu2.rb
- rebase this branch onto `FI-3431-us-core-090`
- add `bulk_data_test_kit` to the Gemfile or gemspec
- `bundle install`
- add `require 'bulk_data_test_kit'` to the top of `lib/onc_certification_g10_test_kit.rb`
- `bundle exec inferno c` should load without error
> FI-3381: Remove duplicate id

- config/presets/g10_reference_server_preset.json
This ticket address (g)(10) part of FI-3430
What's changed:
* Sort preset scope alphabetically with `[patient|user]/Patient.[read|rs]`
* Remove `[patient|user]/Media.[read|rs]` for US Core 6.1.0 scopes
* Add `[patient|user]/Endpoint.[read|rs]` to US Core 7.0.0 scopes
> FI-3430 Sort (g)(10) preset scope

- config/presets/g10_reference_server_preset.json
Error caused by the Endpoint.rs scope causing test 1.4.08 to fail has been fixed.
PractitionerRole.endpoint is a MS element, so the reference resolve test needs to read the Endpoint resource referenced by PractitionerRole. However, PractitionerRole is an optional resource for US Core v7, so the g10 test kit does not have a PractitionerRole test group.  Therefore, we did not need to make changes to the SMART tests and add the Endpoint.rs scope, and thus the fix for this issue was removing all patient/Endpoint.rs and user/Endpoint.rs from the g10 preset.
Run the g10 test kit locally and ensure the patient/Endpoint.rs and user/Endpoint.rs scopes were removed from the g10 preset, and ensure test 1.4.08 passes locally.
> FI-3595: Fix Reference Server Preset Endpoint Scope

- lib/onc_certification_g10_test_kit/short_id_map.yml
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
This branch adds a failing test to the discovery group in the standalone patient app group when US Core 7 and SMART App Launch 1 are selected.
> FI-3428: Prevent systems from passing with US core 7 and SMART App Launch 1

- .github/workflows/publish-docs-wiki.yml
Allows users to 'preview' docs changes to the wiki, as in practice it is hard to ensure that docs changes look and work properly within the wiki which ends up creating a lot of junk PRs.  Enables the workflow to be run manually via the Actions against any branch.  ~Also automatically resynchs wiki docs to `main` on closure for any PR that has docs changes, just in case it was manually synchronized but not undone.~ (removed that run-on-close feature because it is spammy on merges, which counts as a PR closure)
Originally I created a workflow that would synchronize to the wiki automatically if a title contained something like '(DOCS)' in it.
But this requires people to know that this functionality exists.  And at that point, it just seems simpler to allow manual execution of this via the …
> FI-3642 Updates wiki workflow to allow manual synchronization for previewing.

- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_4_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_5_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_6_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_7_api_group.rb
This branch alters how g10 imports tests from US Core so that it doesn't alter the original groups in US Core.
On main, run `bundle exec inferno c`. Then in the console, run `USCoreTestKit::USCoreV311::USCoreTestSuite.groups[1].groups[-5].ancestors[1].children`. You will see that it does not include any search tests because that group was altered during by the `reject!` call in the g10 import. If you do the same on this branch, you should see that the search tests are still there since now the imported group is being altered rather than the original source group.
The groups in g10 should contain the same tests as they do on main.
> FI-3728: Fix importing to not alter the imported groups

- .env
- .env.development
- .env.production
- config/nginx.background.conf
- config/nginx.conf
- docker-compose.background.yml
- docker-compose.yml
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/configuration_checker.rb
- lib/onc_certification_g10_test_kit/feature.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_validation_spec.rb
- spec/onc_certification_g10_test_kit/resource_validation_spec.rb
Removes all logic and settings specific to the legacy inferno-validator-wrapper. Now that we've been using the HL7 validator successfully in production for a while, there's no need to keep it around.
Refer to #488 and #497 for the original changes
Run the g10 tests as usual, there should be no visible impact to anything
> FI-3513: Remove legacy validator support

- docker-compose.background.yml
- lib/onc_certification_g10_test_kit/configuration_checker.rb
Bump the validator service to version 1.0.65 which is the most recent as of today. (https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/releases) This uses the core HL7 validator version 6.5.17 (https://github.com/hapifhir/org.hl7.fhir.core/releases)
This release has no breaking changes to the validation service API or configuration options, and does not introduce any new error messages for our reference server data based on testing against all 4 g10 x US Core version options. The biggest change is a new environment variable that allows for configuring the presets loaded at service startup. Our image defaults this env var such that no presets are loaded.
> FI-3867: Bump validator to v1.0.65

- lib/onc_certification_g10_test_kit/multi_patient_api_stu1.rb
This branch prevents an extra `url` input from appearing for the Multi-Patient API STU1 (see https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/645). On prod, when running the Multi-Patient API STU1 group, you can see the extra input as shown in the above issue, which is no longer present on this branch.
> FI-3993: Remove extra bulk data url input

- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
We reorganized the wiki, and we missed updating this link to the renamed page.  I did a search of the repo and didn't find any other links to the wiki that didn't work.
Also, I added a temporary page in the wiki manually to link people to the right spot; however, this will be wiped out the next time we make a change to the docs/ directory in the repo.
h/t @edeyoung 
Something we should consider doing is asking on Zulip if there is a need to maintain this any more.  At this point, IE is well past the sunset date; though, these types of things tend to take longer to retire in practice.
> FI-3915 Fix outdated link to IE Browser launch instructions in documentation.
