onc-healthit/onc-certification-g10-test-kit

- .gitignore
- .rubocop.yml
- Gemfile
- Gemfile.lock
- Rakefile
- g10_certification_test_kit.gemspec
- lib/g10_certification_test_kit.rb
- lib/inferno/ext/bloomer.rb
- lib/inferno/repositiories/validators.rb
- lib/inferno/terminology/bcp47.rb
- lib/inferno/terminology/codesystem.rb
- lib/inferno/terminology/fhir_package_manager.rb
- lib/inferno/terminology/loader.rb
- lib/inferno/terminology/tasks.rb
- lib/inferno/terminology/tasks/check_built_terminology.rb
- lib/inferno/terminology/tasks/count_codes_in_value_set.rb
- lib/inferno/terminology/tasks/create_value_set_validators.rb
- lib/inferno/terminology/tasks/expand_value_set_to_file.rb
- lib/inferno/terminology/tasks/process_umls.rb
- lib/inferno/terminology/tasks/process_umls_translations.rb
- lib/inferno/terminology/tasks/run_umls_jar.rb
- lib/inferno/terminology/terminology_validation.rb
- lib/inferno/terminology/validator.rb
- lib/inferno/terminology/value_set.rb
- spec/spec_helper.rb
This branch adds rubocop using a similar configuration as inferno core.
> Add rubocop

- Gemfile.lock
- lib/g10_certification_test_kit.rb
- lib/g10_certification_test_kit/limited_scope_grant_test.rb
- lib/g10_certification_test_kit/resource_access_test.rb
- lib/g10_certification_test_kit/restricted_access_test.rb
- lib/g10_certification_test_kit/restricted_resource_type_access_group.rb
- lib/g10_certification_test_kit/smart_limited_app_group.rb
- lib/g10_certification_test_kit/smart_standalone_patient_app_group.rb
- lib/g10_certification_test_kit/unrestricted_resource_type_access_group.rb
- spec/g10_certification_test_kit/patient_context_test_spec.rb
- spec/g10_certification_test_kit/resource_access_test_spec.rb
This branch adds tests for unrestricted access and for the limited app launch.
> FI-1363: Limited access tests

- lib/onc_certification_g10_test_kit.rb
We will need to add information about bulk data as well.
Note: I'm having some network problems and docker is having trouble pull down git repos for dependencies for some reason.  So definitely take a look at it in the interface as part of the review.
> Update instructions and name.

- README.md
If looks OK please go ahead and merge.  I think we need to beef up our installation instructions a bit, but first we just need to get the existing language about it being a 'preview version' out of there.
> Initial README updates.

- lib/onc_certification_g10_test_kit/bulk_data_group_export.rb
- spec/onc_certification_g10_test_kit/bulk_data_group_export_spec.rb
Added accept header to `get` request made in test 5.2.05 to address discrepancy noted [here](https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/47). This PR fixes GitHub Issue #47
> FI-1498-accept-headers

- Gemfile.lock
- lib/onc_certification_g10_test_kit/multi_patient_api.rb
- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/smart_app_launch_invalid_aud_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_invalid_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_invalid_token_group.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
- lib/onc_certification_g10_test_kit/smart_public_standalone_launch_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- lib/onc_certification_g10_test_kit/token_revocation_group.rb
- onc_certification_g10_test_kit.gemspec
- spec/onc_certification_g10_test_kit/resource_access_test_spec.rb
This branch cleans up the order and labeling of the inputs. This branch has to be tested by loading it in the inferno core repo, because it relies on functionality that hasn't yet been released.
> FI-1410: Update input forms

- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
Ensures users will receive error message if using anything but official release version
> Make Version .dev

- lib/onc_certification_g10_test_kit.rb
> isolate the private key so it is not exposed at the public jwks endpoint

- .env
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/authorization_request_builder.rb
add the G10_BULK_DATA_JWKS env var to customize the JWKS used for bulk tests
see more info on #172
> Allow for custom bulk data JWKS

- lib/onc_certification_g10_test_kit.rb
Adds 3 links to the bottom-right side of the page for reporting issues, viewing source, and downloading.
> FI-1661: Customize footer links for g10 test kit (WIP waiting on new inferno core release).

- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
Complimentary to [this PR](https://github.com/inferno-framework/smart-app-launch-test-kit/pull/29)
> FI-1650: Config to Remove Limited App Launch Warning

- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/smart_invalid_pkce_group.rb
This branch adds four scenarios to verify that servers are correctly verifying PKCE parameters.
> FI-1648: Add negative PKCE tests

- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu1.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export_stu2.rb
Implementing [this ticket.](https://oncprojectracking.healthit.gov/support/secure/RapidBoard.jspa?rapidView=40&projectKey=FI&view=detail&selectedIssue=FI-1581&quickFilter=183)
> FI-1581: Check that output file array contains absolute urls 

- Gemfile
- Gemfile.lock
- onc_certification_g10_test_kit.gemspec
Cherry-picked from @Jammjammjamm's commit.  It would be helpful to have this merged in separately from the restricted access tests in case that doesn't get merged in immediately.
> use official us core release

- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
Adds checks for `authorize-post`, `permission-v1`, and `permission-v2` capabilties.
Set `SMART_2_ENABLED=true` environment variable (can be done in the appropriate `.env` file)
Run the application normally or with `ASYNC_JOBS=false bundle exec puma `
> FI-1600: Additional SMARTv2 Capability Checks

- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
This branch requires GET auth for standalone launch and POST auth for EHR launch when using SMART v2.
> FI-1691: Test  GET and POST auth

- .env
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
- lib/onc_certification_g10_test_kit/bulk_export_validation_tester.rb
- lib/onc_certification_g10_test_kit/feature.rb
- lib/onc_certification_g10_test_kit/profile_selector.rb
- lib/onc_certification_g10_test_kit/restricted_resource_type_access_group.rb
- lib/onc_certification_g10_test_kit/smart_app_launch_invalid_aud_group.rb
- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_limited_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
- lib/onc_certification_g10_test_kit/unrestricted_resource_type_access_group.rb
- lib/onc_certification_g10_test_kit/visual_inspection_and_attestations_group.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
This branch removes the feature flags which are no longer needed since the official release with SVAP support is imminent.
> FI-1692: Remove feature flags

- lib/onc_certification_g10_test_kit/single_patient_us_core_5_api_group.rb
> Fix description to match test group US Core version

- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
> FI-1746: Remove permission-v1 capability requirement for SMART v2

- README.md
Updates README to include all approved versions of standards and provides link to walkthrough, reference server, and onc-hosted instance.
> FI-1763 Update README with SVAP versions and more info.

- lib/onc_certification_g10_test_kit/profile_selector.rb
- spec/onc_certification_g10_test_kit/bulk_export_validation_tester_spec.rb
This PR fixes Github Issue #371 
The changes are:
* Replace the code system url for 'health-concern' in profile_selector
* Add unit test.
> FI-1829 Fix url for health-conern

- lib/onc_certification_g10_test_kit/smart_scopes_test.rb
> FI-1830: Add Media to US Core 5 resource list

- Gemfile.lock
- lib/onc_certification_g10_test_kit/single_patient_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_4_api_group.rb
- lib/onc_certification_g10_test_kit/single_patient_us_core_5_api_group.rb
- onc_certification_g10_test_kit.gemspec
Require support for all required resources types to be listed in the CapabilityStatement (see #399)
> FI-1888: Require all resource types in CapabilityStatement

- config/presets/inferno_reference_server_preset.json
Bulk data and single patient api tests should both work with the preset if you point them at qa.
This shouldn't be merged until right before release when the updated reference server will be deployed.
> FI-2013: Update bulk token endpoint in preset

- README.md
Requirements met for fulfilling ticket [FI-2091](https://oncprojectracking.healthit.gov/support/browse/FI-2091) for this repo.
> FI-2091 Replaced docker-compose with docker compose

- README.md
- lib/onc_certification_g10_test_kit.rb
Make sure that all references to 2015 Edition were replaced.
> FI-2450: Change "2015 Edition Cures Update" to "ONC Certification Program"

- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
This branch adds checks for the additional SMART App Launch core capabilities required by HTI-1.
> FI-2846 - Add additional required capabilities for SMART v2

- lib/onc_certification_g10_test_kit/smart_ehr_practitioner_app_group.rb
- lib/onc_certification_g10_test_kit/smart_standalone_patient_app_group.rb
> FI-2856: Add additional smart capabilities checks

- lib/inferno/terminology/expected_manifest.yml
- resources/value_sets.yml
Rerun the terminology build and the rake task should report success. The test should pass as usual.
> FI-3401: Fix terminology

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/onc_certification_g10_test_kit.rb
- lib/onc_certification_g10_test_kit/version.rb
Update Change Log, Gemfile, and version for (g)(10) v7.0.0 release
> Release 7.0.0

- README.md
- _Footer.md
- _Sidebar.md
- docs/README.md
- docs/SVAP-Update-Guide.md
- docs/Technical-Overview.md
- docs/Terminology-Update-Guide.md
- docs/Unusual-Implementation-Details.md
Some minor docs improvements based on viewing this in the wiki. Most of the changes are already reflected in the [wiki](https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki) because I did it manually in the wiki interface first.  This commits those changes permanently (otherwise this will be rewritten on next merge to main).
> Minor docs visual improvements.

- CHANGELOG.md
- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
Prepare for (g)(10) Test Kit Release v7.0.3
> Relaese v7.0.3

- README.md
- docs/README.md
- docs/Technical-Overview.md
- docs/Terminology-Update-Guide.md
- docs/Unusual-Implementation-Details.md
- docs/Walkthrough.md
- docs/_Footer.md
- docs/_Sidebar.md
I updated some places to add in ASTP as appropriate.  Improved some aspects of the documentation based on some additional lessons learned by iterating on the US Core test kit documentation.  I've proactively synchronized this over to the [wiki](/onc-healthit/onc-certification-g10-test-kit/wiki) (not relevant for the top level README though.
> Various minor docs improvements.

- README.md
- docs/FAQ.md
- docs/IE-Browser.md
- docs/README.md
- docs/SVAP-Update-Guide.md
- docs/SVAP-Updates.md
- docs/Technical-Overview.md
- docs/Terminology-Update-Guide.md
- docs/Unusual-Implementation-Details.md
- docs/Walkthrough.md
Just some minor edits here and there to the docs after running it through an editing tool.  I already deployed a preview over on the Wiki (live here https://github.com/onc-healthit/onc-certification-g10-test-kit/wiki), but its all just minor changes.
> Pass at updating docs.

- CHANGELOG.md
- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
> Release 7.2.1

- Gemfile.lock
- onc_certification_g10_test_kit.gemspec
> Update SMART App Launch Test Kit

- Gemfile.lock
- onc_certification_g10_test_kit.gemspec
Update us_core_test_kit dependency to v0.11.3
> FI-4116 Update us_core_test_kit to v0.11.3

- lib/onc_certification_g10_test_kit/bulk_data_group_export_validation.rb
This PR fixes GitHub issue: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/670
This PR adds http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-clinical-result profile to Multi-Patient Observation Validation Test description for US Core v6 and v7
> FI-4184 Fix Bulk Observation Validation test description

- CHANGELOG.md
- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
Release (g)(10) Test Kit v7.2.4
> Release v7.2.4

- CHANGELOG.md
- Gemfile.lock
- lib/onc_certification_g10_test_kit/version.rb
> Release v7.2.5
